var bingoList = [];

bingoList[1] = [
  { name: "Warm Doublet", types: ["Clothes","Cold Resistance","Hateno",] },
];
bingoList[2] = [
  { name: "5 Koroks", types: ["Korok",] },
  { name: "3 Great Plateau Koroks", types: ["Korok","Plateau",] },
  { name: "Hylian Hood", types: ["Clothes","Hylian Gear","Rupee",] },
  { name: "Hylian Tunic", types: ["Clothes","Hylian Gear","Rupee","Rupee",] },
  { name: "Soup Ladle", types: ["Equipment",] },
  { name: "Any Spicy meal", types: ["Cooking","Cold Resistance",] },
  { name: "Any Tough meal", types: ["Cooking",] },
  { name: "Any Sneaky meal", types: ["Cooking",] },
];
bingoList[3] = [
  { name: "3 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks",] },
  { name: "3 Hateno Koroks", types: ["Korok","Hateno",] },
  { name: "3 Faron Koroks", types: ["Korok","Faron",] },
  { name: "3 Lake Tower Koroks", types: ["Korok","Lake",] },
  { name: "3 Ridgeland Koroks", types: ["Korok","Ridgeland",] },
  { name: "3 Tabantha Koroks", types: ["Korok","Tabantha",] },
  { name: "3 Woodland Koroks", types: ["Korok","Woodland",] },
  { name: "3 Lanayru Koroks", types: ["Korok. Lanayru",] },
  { name: "3 Central Tower Koroks", types: ["Korok","Central Hyrule",] },
  { name: "Hylian Trousers", types: ["Clothes","Hylian Gear","Rupee",] },
  { name: "The Priceless Maracas' Side Quest", types: ["Side Quest","Dueling Peaks",] },
  { name: "1 Koko Cooking Side Quest", types: ["Side Quest","Dueling Peaks",] },
  { name: "The Statue's Bargain' Side Quest", types: ["Side Quest","Hateno",] },
  { name: "Watch Out for the Flowers' Shrine Quest", types: ["Shrine","Shrine Quest","Dueling Peaks",] },
  { name: "Any Stalfos 'Arm' Equipment item", types: ["Equipment",] },
  { name: "Any Hearty meal", types: ["Cooking",] },
  { name: "Any Energizing meal", types: ["Cooking","Stamina",] },
  { name: "Any Enduring meal", types: ["Cooking","Stamina",] },
  { name: "Any Hasty meal", types: ["Cooking",] },
  { name: "Any Chilly meal", types: ["Cooking","Wasteland",] },
  { name: "Any Mighty meal", types: ["Cooking",] },
  { name: "Energizing Elixir", types: ["Cooking",] },
  { name: "Enduring Elixir", types: ["Cooking",] },
  { name: "Rock-Hard Food", types: ["Cooking",] },
  { name: "Dubious Food", types: ["Cooking",] },
  { name: "Open 2 Bokoblin Camp Chests", types: ["Plateau",] },
  { name: "Register a Horse", types: ["Horse",] },
  { name: "Anger a Cucco", types: ["Cucco",] },
  { name: "Activate the Dueling Peaks Tower", types: ["Tower","Dueling Peaks",] },
];
bingoList[4] = [
  { name: "10 Koroks", types: ["Korok",] },
  { name: "5 Great Plateau Koroks", types: ["Korok","Plateau",] },
  { name: "3 Wasteland Koroks", types: ["Korok","Wasteland",] },
  { name: "3 Gerudo Koroks", types: ["Korok","Gerudo",] },
  { name: "3 Eldin Koroks", types: ["Korok","Eldin",] },
  { name: "3 Akkala Koroks", types: ["Korok","Akkala",] },
  { name: "Pay 1 Great Fairy", types: ["Rupee","Great Fairy",] },
  { name: "Full Hylian Set", types: ["Clothes","Hylian Gear","Rupee",] },
  { name: "Soldier's Helm", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Stealth Mask", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Climber's Bandanna", types: ["Clothes","Climbing Gear","Dueling Peaks",] },
  { name: "2 Koko Cooking Side Quests", types: ["Side Quest","Dueling Peaks",] },
  { name: "Playtime with Cottla' Side Quest", types: ["Side Quest","Dueling Peaks",] },
  { name: "Wild Horses' Side Quest", types: ["Side Quest","Dueling Peaks","Horse",] },
  { name: "Arrows of Burning Heat' Side Quest", types: ["Side Quest","Dueling Peaks",] },
  { name: "Balloon Flight' Side Quest", types: ["Side Quest","Woodland",] },
  { name: "Riverbed Reward' Side Quest", types: ["Side Quest","Central Hyrule",] },
  { name: "A Minor Test of Strength Shrine", types: ["Shrine","Guardian",] },
  { name: "Any 'Lizal' Equipment item", types: ["Equipment",] },
  { name: "Farming Hoe", types: ["Equipment",] },
  { name: "Boat Oar", types: ["Equipment",] },
  { name: "Any 'Moblin' Equipment item", types: ["Equipment",] },
  { name: "Wooden Mop", types: ["Equipment",] },
  { name: "Fishing Harpoon", types: ["Equipment",] },
  { name: "Any Electro meal", types: ["Cooking",] },
  { name: "Hearty Elixir", types: ["Cooking",] },
  { name: "Spicy Elixir", types: ["Cooking",] },
  { name: "Chilly Elixir", types: ["Cooking",] },
  { name: "Hasty Elixir", types: ["Cooking",] },
  { name: "Mighty Elixir", types: ["Cooking",] },
  { name: "Tough Elixir", types: ["Cooking",] },
  { name: "Sneaky Elixir", types: ["Cooking",] },
  { name: "Save a Traveler in Peril", types: ["Monster",] },
  { name: "Kill a Stone Talus of any kind", types: ["Rupee","Gems","Miniboss","Talus",] },
  { name: "Kill a (normal) Stone Talus", types: ["Rupee","Gems","Miniboss","Talus",] },
  { name: "Kill a Hinox of any kind", types: ["Miniboss","Hinox",] },
  { name: "Kill a Decayed Guardian", types: ["Miniboss","Guardian",] },
  { name: "Give Beedle a Beetle", types: ["Horse",] },
  { name: "Mount a Deer", types: ["Horse",] },
  { name: "Obtain a Purple Rupee", types: ["Rupee",] },
  { name: "Read Paya's Diary", types: ["Dueling Peaks",] },
  { name: "Activate the Faron Tower", types: ["Tower","Faron",] },
  { name: "Activate the Lake Tower", types: ["Tower","Lake",] },
];
bingoList[5] = [
  { name: "6 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks",] },
  { name: "6 Hateno Koroks", types: ["Korok","Hateno",] },
  { name: "6 Faron Koroks", types: ["Korok","Faron",] },
  { name: "6 Lake Tower Koroks", types: ["Korok","Lake",] },
  { name: "6 Ridgeland Koroks", types: ["Korok","Ridgeland",] },
  { name: "3 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "6 Woodland Koroks", types: ["Korok","Woodland",] },
  { name: "6 Akkala Koroks", types: ["Korok","Akkala",] },
  { name: "6 Lanayru Koroks", types: ["Korok. Lanayru",] },
  { name: "6 Central Tower Koroks", types: ["Korok","Central Hyrule",] },
  { name: "Soldier's Armor", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Soldier's Greaves", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Rubber Helm", types: ["Clothes","Rubber Gear","Faron",] },
  { name: "Rubber Armor", types: ["Clothes","Rubber Gear","Ridgeland",] },
  { name: "Stealth Chest Guard", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Stealth Tights", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Flown the Coop' Side Quest", types: ["Side Quest","Dueling Peaks","Heirloom",] },
  { name: "3 Koko Cooking Side Quests", types: ["Side Quest","Dueling Peaks",] },
  { name: "By Firefly's Light' Side Quest", types: ["Side Quest","Dueling Peaks","Heirloom",] },
  { name: "The Hero's Cache' Side Quest", types: ["Side Quest","Hateno",] },
  { name: "Thunder Magnet' Side Quest", types: ["Side Quest","Faron","Rubber Gear",] },
  { name: "The Apple of My Eye' Side Quest", types: ["Side Quest","Tabantha",] },
  { name: "A Gift for the Great Fairy' Side Quest", types: ["Side Quest","Tabantha","Rupee","Great Fairy",] },
  { name: "The Cursed Statue' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno",] },
  { name: "The Two Rings' Shrine Quest", types: ["Shrine","Shrine Quest","Ridgeland",] },
  { name: "Any Boomerang", types: ["Equipment",] },
  { name: "Any Rod weapon", types: ["Equipment","Wizzrobe",] },
  { name: "Fireproof Elixir", types: ["Cooking",] },
  { name: "Kill a Wizzrobe of any kind", types: ["Wizzrobe",] },
  { name: "Kill a fire-typed Wizzrobe", types: ["Wizzrobe",] },
  { name: "Kill a (red) Hinox", types: ["Miniboss","Hinox",] },
  { name: "Read Purah's Diary", types: ["Hateno",] },
  { name: "Activate the Hateno Tower", types: ["Tower","Hateno",] },
  { name: "Activate the Wasteland Tower", types: ["Tower","Wasteland",] },
  { name: "Activate the Ridgeland Tower", types: ["Tower","Ridgeland",] },
  { name: "Activate the Lanayru Tower", types: ["Tower","Lanayru",] },
];
bingoList[6] = [
  { name: "6 Wasteland Koroks", types: ["Korok","Wasteland",] },
  { name: "6 Tabantha Koroks", types: ["Korok","Tabantha",] },
  { name: "Gerudo Set", types: ["Clothes","Wasteland","Rupee",] },
  { name: "Rubber Tights", types: ["Clothes","Rubber Gear","Faron",] },
  { name: "Blue Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Green Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Gray Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "4 Side Quests", types: ["Side Quest",] },
  { name: "Misko, the Great Bandit' Side Quest", types: ["Side Quest","Dueling Peaks",] },
  { name: "The Sheep Rustlers' Side Quest", types: ["Side Quest","Hateno",] },
  { name: "Sunken Treasure' Side Quest", types: ["Side Quest","Hateno",] },
  { name: "The Horseback Hoodlums' Side Quest", types: ["Side Quest","Lake",] },
  { name: "An Ice Guy' Side Quest", types: ["Side Quest","Wasteland",] },
  { name: "A Good-Sized Horse' Side Quest", types: ["Side Quest","Wasteland","Horse",] },
  { name: "The Spark of Romance' Side Quest", types: ["Side Quest","Tabantha",] },
  { name: "The Royal White Stallion' Side Quest", types: ["Side Quest","Central Hyrule","Horse","Stamina",] },
  { name: "Crowned Beast' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno","Horse",] },
  { name: "A Landscape of a Stable' Shrine Quest", types: ["Shrine","Shrine Quest","Eldin",] },
  { name: "Any 'Zora' Equipment item", types: ["Equipment",] },
  { name: "Any Fire-typed Equipment item", types: ["Equipment",] },
  { name: "Any Ice-typed Equipment item", types: ["Equipment",] },
  { name: "Any Electric-typed Equipment item", types: ["Equipment",] },
  { name: "3 Identical Weapons", types: ["Equipment",] },
  { name: "Electro Elixir", types: ["Cooking",] },
  { name: "Any Fairy Tonic", types: ["Cooking",] },
  { name: "Hard-Boiled Egg", types: ["Cooking",] },
  { name: "Glazed Meat", types: ["Cooking",] },
  { name: "Salt-Grilled Crab", types: ["Cooking",] },
  { name: "Kill an ice-typed Wizzrobe", types: ["Wizzrobe",] },
  { name: "Kill an electric-typed Wizzrobe", types: ["Wizzrobe",] },
  { name: "Register the Royal Horse", types: ["Horse","Central Hyrule","Stamina",] },
  { name: "Obtain a Silver Rupee", types: ["Rupee",] },
  { name: "Activate the Tabantha Tower", types: ["Tower","Tabantha",] },
  { name: "Activate the Woodland Tower", types: ["Tower","Woodland",] },
  { name: "Activate the Central Tower", types: ["Tower","Central Hyrule",] },
];
bingoList[7] = [
  { name: "15 Koroks", types: ["Korok",] },
  { name: "9 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks",] },
  { name: "9 Hateno Koroks", types: ["Korok","Hateno",] },
  { name: "9 Lake Tower Koroks", types: ["Korok","Lake",] },
  { name: "6 Gerudo Koroks", types: ["Korok","Gerudo",] },
  { name: "9 Tabantha Koroks", types: ["Korok","Tabantha",] },
  { name: "6 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "6 Eldin Koroks", types: ["Korok","Eldin",] },
  { name: "9 Central Tower Koroks", types: ["Korok","Central Hyrule",] },
  { name: "Hylian Hood ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Hylian Tunic ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Snowquill Tunic", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Snowquill Trousers", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Flamebreaker Armor", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Flamebreaker Boots", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Zora Helm", types: ["Clothes","Zora Gear","Lanayru",] },
  { name: "Zora Armor", types: ["Clothes","Zora Gear","Lanayru",] },
  { name: "Climbing Boots", types: ["Clothes","Climbing Gear","Hateno",] },
  { name: "Snow Boots", types: ["Clothes","Boots","Side Quest","Gerudo",] },
  { name: "Red Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Yellow Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Black Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Purple Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Light Blue Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Navy Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Orange Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Peach Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Crimson Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Light Yellow Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Brown Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "4 Koko Cooking Side Quests", types: ["Side Quest","Dueling Peaks",] },
  { name: "A Gift of Nightshade' Side Quest", types: ["Side Quest","Faron",] },
  { name: "The Secret Club's Secret' Side Quest", types: ["Side Quest","Wasteland","Radiant Gear","Desert Gear",] },
  { name: "Diving is Beauty!' Side Quest", types: ["Side Quest","Lanayru",] },
  { name: "A Rare Find' Side Quest", types: ["Side Quest","Central Hyrule",] },
  { name: "3 Dueling Peaks Shrines", types: ["Shrine","Dueling Peaks",] },
  { name: "Twin Memories' shrines", types: ["Shrine","Shrine Quest","Dueling Peaks",] },
  { name: "Song of Storms' Shrine Quest", types: ["Shrine","Shrine Quest","Faron",] },
  { name: "Any 'Forest Dweller's' Equipment item", types: ["Equipment",] },
  { name: "Any 'Boko' Equipment item", types: ["Equipment",] },
  { name: "Any 'Rusty' Equipment item", types: ["Equipment",] },
  { name: "Any Guardian Sword", types: ["Equipment","Guardian",] },
  { name: "Any Ancient Battle Axe", types: ["Equipment","Guardian",] },
  { name: "Any Guardian Spear", types: ["Equipment","Guardian",] },
  { name: "3 Identical Shields", types: ["Equipment",] },
  { name: "3 Identical Bows", types: ["Equipment",] },
  { name: "Apple Pie", types: ["Cooking","Tabantha",] },
  { name: "Copious Fish Skewers", types: ["Cooking",] },
  { name: "Kill a Stone Talus (Luminous)", types: ["Rupee","Gems","Miniboss","Talus",] },
  { name: "Kill a Blue Hinox", types: ["Miniboss","Hinox",] },
  { name: "Kill a Guardian Stalker", types: ["Miniboss","Guardian",] },
  { name: "5 Heart Containers", types: ["Shrine","Heart",] },
  { name: "2 Stamina Vessels", types: ["Shrine","Stamina",] },
  { name: "Read Robbie's Diary", types: ["Akkala",] },
  { name: "500m in the Gliding Minigame", types: ["Minigame","Ridgeland",] },
  { name: "5 Deer in Hunting Minigame", types: ["Minigame","Hateno",] },
  { name: "Activate the Gerudo Tower", types: ["Tower","Gerudo",] },
  { name: "Activate the Eldin Tower", types: ["Tower","Eldin",] },
];
bingoList[8] = [
  { name: "7 Great Plateau Koroks", types: ["Korok","Plateau",] },
  { name: "9 Faron Koroks", types: ["Korok","Faron",] },
  { name: "9 Ridgeland Koroks", types: ["Korok","Ridgeland",] },
  { name: "9 Akkala Koroks", types: ["Korok","Akkala",] },
  { name: "9 Lanayru Koroks", types: ["Korok. Lanayru",] },
  { name: "Hylian Trousers ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Full Soldier's Set", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Snowquill Headdress", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Barbarian Armor", types: ["Clothes","Barbarian Gear","Wasteland",] },
  { name: "White Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Sunshroom Sensing' Side Quest", types: ["Side Quest","Hateno","Camera",] },
  { name: "What's for Dinner?' Side Quest", types: ["Side Quest","Faron",] },
  { name: "Take Back the Sea' Side Quest", types: ["Side Quest","Faron",] },
  { name: "Hunt for the Giant Horse' Side Quest", types: ["Side Quest","Lake","Horse","Stamina",] },
  { name: "Tools of the Trade' Side Quest", types: ["Side Quest","Wasteland","Gems",] },
  { name: "Missing in Action' Side Quest", types: ["Side Quest","Wasteland",] },
  { name: "Fireproof Lizard Roundup' Side Quest", types: ["Side Quest","Eldin","Flame Gear",] },
  { name: "A Freezing Rod' Side Quest", types: ["Side Quest","Woodland","Wizzrobe",] },
  { name: "8 Shrines", types: ["Shrine",] },
  { name: "3 Lake Shrines", types: ["Shrine","Lake",] },
  { name: "3 Ridgeland Shrines", types: ["Shrine","Ridgeland",] },
  { name: "3 Central Tower Shrines", types: ["Shrine","Central Hyrule",] },
  { name: "The Eye of the Sandstorm' Shrine Quest", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "Into the Vortex' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala",] },
  { name: "Master of the Wind' Shrine Quest", types: ["Shrine","Shrine Quest","Lanayru",] },
  { name: "Any Guardian Shield", types: ["Equipment","Guardian",] },
  { name: "Fruitcake", types: ["Cooking",] },
  { name: "Curry Pilaf", types: ["Cooking",] },
  { name: "Wildberry Crepe", types: ["Cooking","Tabantha",] },
  { name: "Cream of Mushroom Soup", types: ["Cooking",] },
  { name: "Register the Giant Horse", types: ["Horse","Lake","Stamina",] },
  { name: "Talk to Kilton", types: ["Kilton","Akkala",] },
  { name: "Obtain a Gold Rupee", types: ["Rupee",] },
  { name: "Finish Golf Minigame", types: ["Minigame","Woodland",] },
  { name: "Activate the Hebra Tower", types: ["Tower","Hebra","Cold Resistance",] },
  { name: "Activate the Akkala Tower", types: ["Tower","Akkala",] },
];
bingoList[9] = [
  { name: "20 Koroks", types: ["Korok",] },
  { name: "9 Wasteland Koroks", types: ["Korok","Wasteland",] },
  { name: "9 Woodland Koroks", types: ["Korok","Woodland",] },
  { name: "9 Eldin Koroks", types: ["Korok","Eldin",] },
  { name: "Desert Voe Headband", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Desert Voe Spaulder", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Desert Voe Trousers", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Rubber Helm ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy",] },
  { name: "Stealth Mask ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Stealth Chest Guard ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Stealth Tights ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Climber's Bandanna ★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Barbarian Helm", types: ["Clothes","Barbarian Gear","Akkala",] },
  { name: "Amber Earrings", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "3 Side Quests", types: ["Side Quest",] },
  { name: "6 Side Quests", types: ["Side Quest",] },
  { name: "A Gift for My Beloved' Side Quest", types: ["Side Quest","Hateno",] },
  { name: "A Royal Recipe' Side Quest", types: ["Side Quest","Central Hyrule","Cooking",] },
  { name: "4 Shrine Quests", types: ["Shrine","Shrine Quest",] },
  { name: "3 Hateno Shrines", types: ["Shrine","Hateno",] },
  { name: "3 Faron Shrines", types: ["Shrine","Faron",] },
  { name: "3 Tabantha Shrines", types: ["Shrine","Tabantha",] },
  { name: "A Modest Test of Strength Shrine", types: ["Shrine","Guardian",] },
  { name: "Secret of the Cedars' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno",] },
  { name: "The Desert Labyrinth' Shrine Quest", types: ["Shrine","Shrine Quest","Wastelands","Barbarian Gear",] },
  { name: "Cliffside Etchings' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo","Cold Resistance",] },
  { name: "Sign of the Shadow' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo",] },
  { name: "Forgotten Temple Shrine", types: ["Shrine","Shrine Quest","Woodland",] },
  { name: "Shrouded Shrine' Shrine Quest", types: ["Shrine","Shrine Quest","Woodland",] },
  { name: "1 Korok Trial", types: ["Shrine","Shrine Quest","Woodland",] },
  { name: "The Gut Check Challenge' Shrine Quest", types: ["Shrine","Shrine Quest","Eldin",] },
  { name: "The Skull's Eye' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala",] },
  { name: "Any 'Royal Guard's' Equipment item", types: ["Equipment",] },
  { name: "Any second tier Rod weapon", types: ["Equipment","Wizzrobe",] },
  { name: "Monster cake", types: ["Cooking","Kilton",] },
  { name: "Kill a Igneo Talus", types: ["Rupee","Gems","Miniboss","Talus","Eldin",] },
  { name: "Kill a Stone Talus (Rare)", types: ["Rupee","Miniboss","Talus",] },
  { name: "Mount a Bear", types: ["Horse","Stamina",] },
  { name: "Mount a Stalhorse", types: ["Horse",] },
];
bingoList[10] = [
  { name: "12 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks",] },
  { name: "12 Hateno Koroks", types: ["Korok","Hateno",] },
  { name: "12 Lake Tower Koroks", types: ["Korok","Lake",] },
  { name: "9 Gerudo Koroks", types: ["Korok","Gerudo",] },
  { name: "12 Tabantha Koroks", types: ["Korok","Tabantha",] },
  { name: "9 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "12 Central Tower Koroks", types: ["Korok","Central Hyrule",] },
  { name: "Soldier's Helm ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Soldier's Armor ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Soldier's Greaves ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Rubber Armor ★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy",] },
  { name: "Rubber Tights ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy",] },
  { name: "Flamebreaker Helm", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Climbing Gear", types: ["Clothes","Climbing Gear","Hateno",] },
  { name: "Barbarian Leg Wraps", types: ["Clothes","Barbarian Gear","Hebra",] },
  { name: "Radiant Mask", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Radiant Shirt", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "9 Shrines", types: ["Shrine",] },
  { name: "3 Wasteland Shrines", types: ["Shrine","Wasteland",] },
  { name: "3 Woodland Shrines", types: ["Shrine","Woodland",] },
  { name: "3 Eldin Shrines", types: ["Shrine","Eldin",] },
  { name: "3 Akkala Shrines", types: ["Shrine","Akkala",] },
  { name: "The Silent Swordswomen' Shrine Quest", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "The Seven Heroines' Shrine Quest", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "Secret of the Snowy Peaks' Shrine Quest", types: ["Shrine","Shrine Quest","Wastelands","Cold Resistance",] },
  { name: "Test of Will' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo",] },
  { name: "Akkala 'Trial of the Labyrinth' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala","Barbarian Gear",] },
  { name: "Kill a Frost Talus", types: ["Rupee","Gems","Miniboss","Talus","Cold Resistance",] },
  { name: "Kill a Lynel", types: ["Miniboss","Lynel",] },
  { name: "Kill a Gaurdian Turret", types: ["Miniboss","Guardian","Hyrule Castle",] },
  { name: "5 Equipment in Compendium", types: ["Camera","Compendium",] },
  { name: "Read Zelda's Diary", types: ["Hyrule Castle",] },
  { name: "Read King's Diary", types: ["Hyrule Castle",] },
  { name: "Take a Selfie with Hestu", types: ["Dueling Peaks","Camera",] },
  { name: "Sheikah Sensor +", types: ["Camera","Rune Upgrade","Hateno",] },
  { name: "Finish Basic Shield Surfing Minigame", types: ["Minigame","Hebra","Cold Resistance",] },
  { name: "Strike in Bowling Minigame", types: ["Minigame","Hebra","Cold Resistance",] },
  { name: "3 Shrines in the Lanayru Region", types: ["Shrine","Lanayru",] },
];
bingoList[11] = [
  { name: "12 Faron Koroks", types: ["Korok","Faron",] },
  { name: "12 Wasteland Koroks", types: ["Korok","Wasteland",] },
  { name: "12 Ridgeland Koroks", types: ["Korok","Ridgeland",] },
  { name: "12 Woodland Koroks", types: ["Korok","Woodland",] },
  { name: "12 Akkala Koroks", types: ["Korok","Akkala",] },
  { name: "12 Lanayru Koroks", types: ["Korok. Lanayru",] },
  { name: "Pay 2 Great Fairies", types: ["Rupee","Great Fairy",] },
  { name: "Champion's Tunic", types: ["Clothes","Champion","Camera",] },
  { name: "Zora Armor ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos",] },
  { name: "Zora Greaves", types: ["Clothes","Zora Gear","Lanayru","Camera",] },
  { name: "Full Stealth Set", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Climbing Boots ★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Radiant Tights", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Topaz Earrings", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "Curry for What Ails You' Side Quest", types: ["Side Quest","Tabantha","Eldin",] },
  { name: "Lynel Safari' Side Quest", types: ["Side Quest","Lanayru","Camera","Zora Gear",] },
  { name: "The Royal Guard's Gear' Side Quest", types: ["Side Quest","Hyrule Castle",] },
  { name: "10 Shrines", types: ["Shrine",] },
  { name: "3 Hebra Shrines", types: ["Shrine","Hebra","Cold Resistance",] },
  { name: "Fragmented Monument' Shrine Quest", types: ["Shrine","Shrine Quest","Faron","Camera",] },
  { name: "The Serpent's Jaws' Shrine Quest", types: ["Shrine","Shrine Quest","Lake","Dragon",] },
  { name: "Hebra Labyrinth 'Trial on the Cliff' Shrine Quest", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance","Barbarian Gear",] },
  { name: "Collect 1 Picture Memory", types: ["Camera",] },
  { name: "1 Fire, 1 Ice, and 1 Electric weapons", types: ["Equipment",] },
  { name: "Kill a Black Hinox", types: ["Miniboss","Hinox",] },
  { name: "Kill a Stalnox", types: ["Miniboss","Hinox",] },
  { name: "Kill a Guardian Skywatcher", types: ["Miniboss","Guardian",] },
  { name: "Kill a Molduga", types: ["Miniboss","Molduga","Wasteland",] },
  { name: "5 Creatures in Compendium", types: ["Camera","Compendium",] },
  { name: "2000 Rupees", types: ["Rupee",] },
  { name: "Take a Selfie with Kass", types: ["Camera",] },
  { name: "Obtain a Material from Farosh", types: ["Dragon",] },
  { name: "Obtain a Material from Dinraal", types: ["Dragon",] },
  { name: "Remote Bomb +", types: ["Camera","Rune Upgrade","Hateno",] },
  { name: "Activate 4 Towers", types: ["Tower",] },
];
bingoList[12] = [
  { name: "12 Eldin Koroks", types: ["Korok","Eldin",] },
  { name: "Snowquill Tunic ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Snowquill Trousers ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Flamebreaker Boots ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Zora Helm ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos",] },
  { name: "Opal Earrings", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "Sapphire Circlet", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "Ruby Circlet", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "Bokoblin Mask", types: ["Clothes","Kilton",] },
  { name: "5 Side Quests", types: ["Side Quest",] },
  { name: "The Eighth Heroine' Side Quest", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera",] },
  { name: "Death Mountain's Secret' Side Quest", types: ["Side Quest","Eldin",] },
  { name: "The Road to Respect' Side Quest", types: ["Side Quest","Eldin","Talus",] },
  { name: "Little Sister's Big Request' Side Quest", types: ["Side Quest","Akkala",] },
  { name: "Legendary Rabbit Trial' Side Quest", types: ["Side Quest","Wasteland","Camera",] },
  { name: "5 Shrine Quests", types: ["Shrine","Shrine Quest",] },
  { name: "3 Gerudo Shrines", types: ["Shrine","Gerudo","Cold Resistance",] },
  { name: "Stranded on Eventide' Shrine Quest", types: ["Shrine","Shrine Quest","Faron",] },
  { name: "Three Giant Brothers' Shrine Quest", types: ["Shrine","Shrine Quest","Faron","Hinox",] },
  { name: "The Bird in the Mountains' Shrine Quest", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance",] },
  { name: "Any 'Lynel' Equipment item", types: ["Equipment","Lynel",] },
  { name: "5 Monsters in Compendium", types: ["Camera","Compendium",] },
  { name: "6 Heart Containers", types: ["Shrine","Heart",] },
  { name: "3 Stamina Vessels", types: ["Shrine","Stamina",] },
  { name: "Take a Selfie with Sidon", types: ["Lanayru","Camera",] },
  { name: "Obtain a Material from Naydra", types: ["Hateno","Cold Resistance","Dragon",] },
];
bingoList[13] = [
  { name: "25 Koroks", types: ["Korok",] },
  { name: "15 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks",] },
  { name: "15 Hateno Koroks", types: ["Korok","Hateno",] },
  { name: "15 Lake Tower Koroks", types: ["Korok","Lake",] },
  { name: "12 Gerudo Koroks", types: ["Korok","Gerudo",] },
  { name: "15 Ridgeland Koroks", types: ["Korok","Ridgeland",] },
  { name: "15 Tabantha Koroks", types: ["Korok","Tabantha",] },
  { name: "12 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "15 Central Tower Koroks", types: ["Korok","Central Hyrule",] },
  { name: "Pay Horse God Malanya", types: ["Lake","Rupee",] },
  { name: "Snowquill Headdress ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Full Snowquill Set", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Desert Voe Spaulder ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Desert Voe Trousers ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Flamebreaker Armor ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Sand Boots", types: ["Clothes","Boots","Side Quest","Gerudo",] },
  { name: "Snow Boots ★", types: ["Clothes","Boots","Side Quest","Great Fairy",] },
  { name: "Slated for Upgrades' Side Quest", types: ["Side Quest","Hateno","Camera",] },
  { name: "Medicinal Molduga' Side Quest", types: ["Side Quest","Wasteland","Molduga",] },
  { name: "Stalhorse: Pictured!' Side Quest", types: ["Side Quest","Hebra","Camera",] },
  { name: "A Shady Customer' Side Quest", types: ["Side Quest","Akkala","Kilton","Camera",] },
  { name: "11 Shrines", types: ["Shrine",] },
  { name: "The Spring of Wisdom' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno","Cold Resistance","Dragon",] },
  { name: "The Spring of Power' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala","Dragon",] },
  { name: "The Ceremonial Song' Shrine Quest", types: ["Shrine","Shrine Quest","Lanayru",] },
  { name: "Collect 2 Picture Memories", types: ["Camera",] },
  { name: "Hylian Shield", types: ["Miniboss","Hinox","Hyrule Castle",] },
  { name: "Kill Coliseum Lynel", types: ["Miniboss","Lynel","Central Hyrule",] },
  { name: "Mount the Lord of the Mountain", types: ["Horse","Ridgeland","Stamina",] },
  { name: "Take a Selfie with Riju", types: ["Wasteland","Camera",] },
  { name: "Take a Selfie while on fire", types: ["Eldin","Camera",] },
  { name: "Stasis +", types: ["Camera","Rune Upgrade","Hateno",] },
  { name: "20 Targets in Flight Range Minigame", types: ["Minigame","Tabantha","Cold Resistance",] },
  { name: "Activate 5 Towers", types: ["Tower",] },
];
bingoList[14] = [
  { name: "15 Faron Koroks", types: ["Korok","Faron",] },
  { name: "15 Wasteland Koroks", types: ["Korok","Wasteland",] },
  { name: "15 Woodland Koroks", types: ["Korok","Woodland",] },
  { name: "15 Akkala Koroks", types: ["Korok","Akkala",] },
  { name: "15 Lanayru Koroks", types: ["Korok. Lanayru",] },
  { name: "Champion's Tunic ★", types: ["Clothes","Champion","Camera","Great Fairy",] },
  { name: "Desert Voe Headband ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Full Desert Voe Set", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Full Rubber Set", types: ["Clothes","Rubber Gear","Faron","Ridgeland",] },
  { name: "Climbing Gear ★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Barbarian Armor ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel",] },
  { name: "Radiant Shirt ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy",] },
  { name: "Diamond Circlet", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "8 Side Quests", types: ["Side Quest",] },
  { name: "A Major Test of Strength Shrine", types: ["Shrine","Guardian",] },
  { name: "Guardian Slideshow' Shrine Quest", types: ["Shrine","Shrine Quest","Lake","Camera","Guardian",] },
  { name: "1 Divine Beast Main Quest", types: ["Divine Beast",] },
  { name: "Collect 3 Picture Memories", types: ["Camera",] },
  { name: "Windcleaver", types: ["Equipment","Wasteland",] },
  { name: "10 Creatures in Compendium", types: ["Camera","Compendium",] },
  { name: "10 Equipment in Compendium", types: ["Camera","Compendium",] },
];
bingoList[15] = [
  { name: "30 Koroks", types: ["Korok",] },
  { name: "15 Gerudo Koroks", types: ["Korok","Gerudo",] },
  { name: "15 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "15 Eldin Koroks", types: ["Korok","Eldin",] },
  { name: "Zora Greaves ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos","Camera",] },
  { name: "Full Climber's Set", types: ["Clothes","Climbing Gear",] },
  { name: "Barbarian Helm ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel",] },
  { name: "Barbarian Leg Wraps ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel",] },
  { name: "Radiant Mask ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy",] },
  { name: "Radiant Tights ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy",] },
  { name: "Amber Earrings ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "7 Side Quests", types: ["Side Quest",] },
  { name: "Find Kheel' Side Quest", types: ["Side Quest","Tabantha",] },
  { name: "The Jewel Trade' Side Quest", types: ["Side Quest","Eldin","Gems",] },
  { name: "Robbie's Research' Side Quest", types: ["Side Quest","Akkala","Camera",] },
  { name: "12 Shrines", types: ["Shrine",] },
  { name: "Divine Best Vah Medoh' Main Quest", types: ["Divine Beast","Tabantha","Cold Resistance",] },
  { name: "Revali's Gale", types: ["Divine Beast","Tabantha","Cold Resistance",] },
  { name: "Spring-Loaded Hammer", types: ["Equipment","Kilton",] },
  { name: "10 Monsters in Compendium", types: ["Camera","Compendium",] },
  { name: "Buy a House", types: ["Hateno","Rupee",] },
];
bingoList[16] = [
  { name: "Flamebreaker Helm ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Topaz Earrings ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "Sapphire Circlet ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "10 Side Quests", types: ["Side Quest",] },
  { name: "The Forgotten Sword' Side Quest", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera",] },
  { name: "Frog Catching' Side Quest", types: ["Side Quest","Lanayru",] },
  { name: "A Wife Washed Away' Side Quest", types: ["Side Quest","Lanayru",] },
  { name: "6 Shrine Quests", types: ["Shrine","Shrine Quest",] },
  { name: "The Stolen Heirloom' Shrine Quest", types: ["Shrine","Shrine Quest","Dueling Peaks","Heirloom","Camera",] },
  { name: "Brother's Roast' Shrine Quest", types: ["Shrine","Shrine Quest","Eldin",] },
  { name: "Divine Best Vah Ruta' Main Quest", types: ["Divine Beast","Lanayru",] },
  { name: "Mipha's Grace", types: ["Divine Beast","Lanayru",] },
  { name: "Collect 4 Picture Memories", types: ["Camera",] },
  { name: "7 Heart Containers", types: ["Shrine","Heart",] },
  { name: "Activate 6 Towers", types: ["Tower",] },
];
bingoList[17] = [
  { name: "35 Koroks", types: ["Korok",] },
  { name: "Hylian Hood ★★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Full Zora Set", types: ["Clothes","Zora Gear","Lanayru","Camera",] },
  { name: "Full Radiant Set", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Opal Earrings ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "Ruby Circlet ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "Luminous Stone Gathering' Side Quest", types: ["Side Quest","Lanayru","Gems",] },
  { name: "13 Shrines", types: ["Shrine",] },
  { name: "The Ancient Rito Song' Shrine Quest", types: ["Shrine","Shrine Quest","Tabantha",] },
  { name: "15 Creatures in Compendium", types: ["Camera","Compendium",] },
  { name: "15 Monsters in Compendium", types: ["Camera","Compendium",] },
  { name: "15 Equipment in Compendium", types: ["Camera","Compendium",] },
  { name: "4 Stamina Vessels", types: ["Shrine","Stamina",] },
  { name: "Upgrade All Runes", types: ["Camera","Rune Upgrade","Hateno",] },
];
bingoList[18] = [
  { name: "Pay 3 Great Fairies", types: ["Rupee","Great Fairy",] },
  { name: "Hylian Tunic ★★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Hylian Trousers ★★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "9 Side Quests", types: ["Side Quest",] },
  { name: "The Giant of Ralis Pond' Side Quest", types: ["Side Quest","Lanayru","Hinox",] },
  { name: "14 Shrines", types: ["Shrine",] },
  { name: "7 Shrine Quests", types: ["Shrine","Shrine Quest",] },
  { name: "Recital at Warbler's Nest' Shrine Quest", types: ["Shrine","Shrine Quest","Tabantha",] },
  { name: "Collect 5 Picture Memories", types: ["Camera",] },
];
bingoList[19] = [
  { name: "Full Flamebreaker Set", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Stealth Mask ★★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Stealth Chest Guard ★★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Stealth Tights ★★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Climber's Bandanna ★★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "The Search for Barta' Side Quest", types: ["Side Quest","Wasteland",] },
  { name: "The Mystery Polluter' Side Quest", types: ["Side Quest","Wasteland",] },
  { name: "Face the Frost Talus' Side Quest", types: ["Side Quest","Tabantha","Hebra","Cold Resistance",] },
  { name: "Riddles of Hyrule' Side Quest", types: ["Side Quest","Woodland","Lynel",] },
  { name: "Divine Best Vah Rudania' Main Quest", types: ["Divine Beast","Eldin",] },
  { name: "Daruk's Protection", types: ["Divine Beast","Eldin",] },
  { name: "Activate 7 Towers", types: ["Tower",] },
];
bingoList[20] = [
  { name: "40 Koroks", types: ["Korok",] },
  { name: "Soldier's Helm ★★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Soldier's Armor ★★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Soldier's Greaves ★★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Rubber Helm ★★", types: ["Clothes","Rubber Gear","Faron","Great Fairy",] },
  { name: "Rubber Armor ★★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy",] },
  { name: "Zora Armor ★★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos",] },
  { name: "Full Barbarian Set", types: ["Clothes","Barbarian Gear",] },
  { name: "12 Side Quests", types: ["Side Quest",] },
  { name: "Leviathan Bones' Side Quest", types: ["Side Quest","Camera",] },
  { name: "15 Shrines", types: ["Shrine",] },
  { name: "8 Shrine Quests", types: ["Shrine","Shrine Quest",] },
  { name: "Divine Best Vah Naboris' Main Quest", types: ["Divine Beast","Wasteland",] },
  { name: "Urbosa's Fury", types: ["Divine Beast","Wasteland",] },
  { name: "20 Equipment in Compendium", types: ["Camera","Compendium",] },
];
bingoList[21] = [
  { name: "45 Koroks", types: ["Korok",] },
  { name: "Rubber Tights ★★", types: ["Clothes","Rubber Gear","Faron","Great Fairy",] },
  { name: "Zora Helm ★★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos",] },
  { name: "Climbing Boots ★★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Diamond Circlet ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "11 Side Quests", types: ["Side Quest",] },
  { name: "Beat Ganon", types: ["Hyrule Castle",] },
  { name: "Collect 6 Picture Memories", types: ["Camera",] },
  { name: "20 Creatures in Compendium", types: ["Camera","Compendium",] },
  { name: "20 Monsters in Compendium", types: ["Camera","Compendium",] },
  { name: "Activate 8 Towers", types: ["Tower",] },
];
bingoList[22] = [
  { name: "Snowquill Tunic ★★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Snowquill Trousers ★★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Flamebreaker Boots ★★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Sand Boots ★", types: ["Clothes","Boots","Side Quest","Great Fairy","Molduga",] },
  { name: "Snow Boots ★★", types: ["Clothes","Boots","Side Quest","Great Fairy",] },
  { name: "16 Shrines", types: ["Shrine",] },
  { name: "Remake a Champion's Weapon or Shield", types: ["Equipment","Divine Beast","Gems",] },
];
bingoList[23] = [
  { name: "50 Koroks", types: ["Korok",] },
  { name: "Desert Voe Headband ★★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Desert Voe Spaulder ★★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Desert Voe Trousers ★★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Flamebreaker Armor ★★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "The Undefeated Champ' Shrine Quest", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "2 Divine Beast Main Quest", types: ["Divine Beast",] },
];
bingoList[24] = [
  { name: "Zora Stone Monuments' Side Quest", types: ["Side Quest","Lanayru",] },
];
bingoList[25] = [
  { name: "", types: ["",] },
  { name: "Side Quests", types: ["",] },
];

$(function() { srl.bingo(bingoList, 5); });