var bingoList = [];

bingoList[1] = [
  { name: "Piko Hammer", types: ["Hammer",] },
  { name: "Carrot Bomb", types: ["Carrot Bomb",] },
  { name: "Speed Boost", types: ["Speed Boost",] },
  { name: "Sunny Beam", types: ["Yellow","Magic",] },
  { name: "Health Plus Badge", types: ["Health Plus","Badge",] },
  { name: "DEF Grow Badge", types: ["DEF Grow","Badge",] },
  { name: "DEF Trade Badge", types: ["DEF Trade","Badge",] },
  { name: "Defeat Green Kotri", types: ["Boss","Kotri","Green Kotri",] },
  { name: "2 Southern Woodland Warp Stones", types: ["Southern Woodland","Warp Stone",] },
  { name: "Hear ♪ Adventure Starts Here", types: ["Music","Southern Woodland",] },
  { name: "Hear ♪ Spectral Cave", types: ["Music","Southern Woodland",] },
  { name: "Hear ♪ Rabi Rabi Beach", types: ["Music","Western Coast",] },
  { name: "Hear ♪ Rabi Rabi Ravine", types: ["Music","Island Core",] },
  { name: "Hear ♪ Home Sweet Home", types: ["Music","Rabi Rabi Town",] },
  { name: "Hear ♪ Miriam's Shop", types: ["Music","Rabi Rabi Town",] },
  { name: "Hear ♪ Bunny Panic!!!", types: ["Music","UPRPRC",] },
  { name: "Hear ♪ Brawl Breaks", types: ["Music","Kotri","Lilith",] },
  { name: "Hear ♪ Get On With It", types: ["Music","Cocoa","Ribbon","Ashuri",] },
];
bingoList[2] = [
  { name: "Rabi Slippers", types: ["Rabi Slippers",] },
  { name: "Lv.2 Speed Boost", types: ["Speed Boost",] },
  { name: "Soul Heart", types: ["Soul Heart",] },
  { name: "Healing Staff", types: ["Green","Magic",] },
  { name: "Quick Barrette", types: ["Barrette","Magic",] },
  { name: "Toxic Strike Badge", types: ["Toxic Strike","Badge",] },
  { name: "Recruit Rita", types: ["Recruit","Rita",] },
  { name: "Recruit Cicini", types: ["Recruit","Cicini",] },
  { name: "5 Warp Stones", types: ["Warp Stone",] },
  { name: "Hear ♪ Forgotten Cave", types: ["Music","Southern Woodland",] },
  { name: "Hear ♪ Starting Forest Night", types: ["Music","Southern Woodland",] },
  { name: "Hear ♪ Pandora's Palace", types: ["Music","Western Coast",] },
  { name: "Hear ♪ Rabi Rabi Park", types: ["Music","Island Core",] },
  { name: "Hear ♪ Inside UPRPRC", types: ["Music","Island Core",] },
  { name: "Hear ♪ Winter Wonderland", types: ["Music","Northern Tundra",] },
  { name: "5% Item", types: ["Collection",] },
];
bingoList[3] = [
  { name: "Max Bracelet", types: ["Bracelet","Magic",] },
  { name: "Book of Carrot", types: ["Book","Magic",] },
  { name: "Hold 3 Rumi Donuts at Once", types: ["Donut",] },
  { name: "Mana Surge Badge", types: ["Mana Surge","Badge",] },
  { name: "ATK Trade Badge", types: ["ATK Trade","Badge",] },
  { name: "ATK and DEF Trade Badges", types: ["ATK Trade","DEF Trade","Badge",] },
  { name: "Defeat Rita", types: ["Boss","Rita",] },
  { name: "Purchase the Defense Up Buff", types: ["Buff","Rita",] },
  { name: "Purchase the Speedy Buff", types: ["Buff","Cicini",] },
  { name: "Log the Speed Down debuff", types: ["Buff","Cicini",] },
  { name: "Log the Poisoned debuff", types: ["Buff",] },
  { name: "Log the Defense Drop debuff", types: ["Buff","Cicini",] },
  { name: "5 Health Up Potions", types: ["Health Up",] },
  { name: "5 Easter Eggs", types: ["Eggs",] },
  { name: "Hear ♪ Golden Riverbank", types: ["Music","Eastern Highlands",] },
  { name: "Hear ♪ Sky-High Bridge", types: ["Music","Island Core",] },
  { name: "Hear ♪ Midstream Jam", types: ["Music","Rita","Lilith",] },
  { name: "Hear ♪ Sandbag Mini Game", types: ["Music",] },
  { name: "Hear ♪ Hi-Tech Duel", types: ["Music","Cicini","Syaro",] },
  { name: "5% Map", types: ["Map",] },
];
bingoList[4] = [
  { name: "Bunny Amulet", types: ["Amulet","Ch2",] },
  { name: "Bunny Whirl", types: ["Whirl","Hammer",] },
  { name: "Hammer Wave", types: ["Wave","Hammer",] },
  { name: "Lv.3 Speed Boost", types: ["Speed Boost",] },
  { name: "Hourglass", types: ["Hourglass","Carrot Bomb","Pandora",] },
  { name: "Rainbow Shot", types: ["Rainbow","Magic","Eggs",] },
  { name: "Auto Earrings", types: ["Earrings","Magic",] },
  { name: "ATK Grow Badge", types: ["ATK Grow","Badge",] },
  { name: "Carrot Boost Badge", types: ["Carrot Boost","Badge",] },
  { name: "Armored Badge", types: ["Armored","Badge",] },
  { name: "Lucky Seven Badge", types: ["Lucky Seven","Badge",] },
  { name: "Recruit Pandora", types: ["Recruit","Pandora",] },
  { name: "Recruit Chocolate", types: ["Recruit","Chocolate",] },
  { name: "Recruit Vanilla", types: ["Recruit","Vanilla",] },
  { name: "Defeat Vanilla", types: ["Boss","Vanilla",] },
  { name: "Defeat 3 UPRPRC Hideout Bosses", types: ["UPRPRC",] },
  { name: "Log the Numb debuff", types: ["Buff",] },
  { name: "5 Mana Up Potions", types: ["Mana Up",] },
  { name: "Hear ♪ Library Ambient", types: ["Music","Western Coast",] },
  { name: "Hear ♪ Exotic Laboratory", types: ["Music","Eastern Highlands",] },
  { name: "Hear ♪ Floating Graveyard", types: ["Music","Western Coast",] },
  { name: "Hear ♪ Plurkwood", types: ["Music","Plurkwood",] },
  { name: "Hear ♪ Icy Summit", types: ["Music","Northern Tundra",] },
  { name: "Hear ♪ Kitty Attack", types: ["Music","Vanilla","Chocolate","Saya","Seana",] },
  { name: "10% Item", types: ["Collection",] },
];
bingoList[5] = [
  { name: "Sliding Powder", types: ["Slide","Lab",] },
  { name: "Lv.2 Bunny Whirl", types: ["Whirl","Hammer",] },
  { name: "Charge Ring", types: ["Ring","Magic","Cocoa",] },
  { name: "Lv.2 Auto Earrings", types: ["Earrings","Magic",] },
  { name: "Weaken Badge", types: ["Weaken","Badge",] },
  { name: "5 Badges", types: ["Badge",] },
  { name: "Defeat Mr. Big Box", types: ["Cicini","Slide","Lab",] },
  { name: "Defeat Holo-Defense System (Rainbow Maid)", types: ["Cicini","Lab",] },
  { name: "Defeat Illusion Alius I", types: ["Boss","Alius","Ch2",] },
  { name: "Purchase the MaxHP Up Buff", types: ["Buff","Chocolate",] },
  { name: "Purchase the MaxMP Up Buff", types: ["Buff","Vanilla",] },
  { name: "Log the Attack Down debuff", types: ["Buff","Alius","Nieve",] },
  { name: "Log the Defense Down debuff", types: ["Buff","Alius","Nixie",] },
  { name: "Hear ♪ Underwater Ambient", types: ["Music","Northern Tundra",] },
  { name: "Hear ♪ Evernight Peak", types: ["Music","Eastern Highlands",] },
  { name: "Hear ♪ Warp Destination", types: ["Music","Warp Destination",] },
  { name: "Hear ♪ Midboss Battle", types: ["Music",] },
  { name: "Hear ♪ Full On Combat", types: ["Music","Lilith","Aruraune","Pandora",] },
  { name: "Hear ♪ Sudden Death", types: ["Music","Alius",] },
  { name: "Equip at least 4 Badges", types: ["Pack Up","Badge",] },
];
bingoList[6] = [
  { name: "Super Carrot", types: ["Super Carrot","Carrot Bomb",] },
  { name: "Lv.2 Sliding Powder", types: ["Slide",] },
  { name: "Bunny Strike", types: ["Slide","Bunny Strike",] },
  { name: "Lv.2 Hammer Wave", types: ["Wave","Hammer",] },
  { name: "Explode Shot", types: ["Red","Magic","Ashuri",] },
  { name: "Healing Staff, Soul Heart, Book of Carrot, and Max Bracelet", types: ["Green","Soul Heart","Book","Bracelet",] },
  { name: "Carrot Bomb, Super Carrot, and Hourglass", types: ["Carrot Bomb","Super Carrot","Hourglass",] },
  { name: "Hold 3 Rumi Cakes at Once", types: ["Cake",] },
  { name: "Arm Strength Badge", types: ["Arm Strength","Badge",] },
  { name: "Frame Cancel Badge", types: ["Frame Cancel","Badge",] },
  { name: "Mana Wager Badge", types: ["Mana Wager","Badge",] },
  { name: "ATK and DEF Grow Badges", types: ["ATK Grow","DEF Grow","Badge",] },
  { name: "Recruit Cocoa", types: ["Recruit","Cocoa","Green Kotri",] },
  { name: "Recruit Chocolate and Vanilla", types: ["Recruit","Chocolate","Vanilla",] },
  { name: "Defeat Ashuri II", types: ["Boss","Ashuri",] },
  { name: "Defeat Blue Kotri", types: ["Boss","Kotri",] },
  { name: "Defeat Shadow Pandora", types: ["Boss","Pandora",] },
  { name: "Visit the computer room in Exotic Lab", types: ["Cicini","Lab",] },
  { name: "Purchase the Arrest Buff", types: ["Buff","Pandora",] },
  { name: "Recruit 3 Towns Members", types: ["Town",] },
  { name: "5 Attack Up Potions", types: ["Attack Up",] },
  { name: "5 Health Up and 5 Mana Up", types: ["Health Up","Mana Up",] },
  { name: "Hear ♪ Sky Island Town", types: ["Music","Western Coast",] },
  { name: "Hear ♪ Aurora Palace", types: ["Music","Northern Tundra",] },
  { name: "10% Map", types: ["Map",] },
];
bingoList[7] = [
  { name: "Light Orb", types: ["Slide","Light Orb",] },
  { name: "Lv.2 Bunny Amulet", types: ["Amulet","Ch2",] },
  { name: "Lv.3 Sliding Powder", types: ["Slide",] },
  { name: "Wall Jump", types: ["Slide","Wall Jump",] },
  { name: "Lv.3 Bunny Whirl", types: ["Whirl","Hammer",] },
  { name: "Lv.3 Hammer Wave", types: ["Wave","Hammer",] },
  { name: "Chaos Rod", types: ["Purple","Magic","Pandora",] },
  { name: "Lv.2 Charge Ring", types: ["Ring","Magic","Cocoa",] },
  { name: "Plus Necklace", types: ["Necklace","Magic",] },
  { name: "Lv.3 Auto Earrings", types: ["Earrings","Magic",] },
  { name: "Obtain a Cocoa Bomb", types: ["Cocoa Bomb","Cocoa","Town",] },
  { name: "Kill a spring board", types: ["Cocoa Bomb",] },
  { name: "Self-Defense Badge", types: ["Self-Defense","Badge",] },
  { name: "Recruit Cocoa, Chocolate, and Vanilla", types: ["Recruit","Cocoa","Chocolate","Vanilla",] },
  { name: "Defeat Illusion Alius III", types: ["Boss","Alius","Ch4",] },
  { name: "Defeat UPRPRC Starting Forest Night", types: ["UPRPRC",] },
  { name: "Log the Stunned debuff", types: ["Buff","Alius",] },
  { name: "Log the Shrink debuff", types: ["Buff","Alius","Ashuri",] },
  { name: "Recruit 4 Towns Members", types: ["Town",] },
  { name: "10 Health Up Potions", types: ["Health Up",] },
  { name: "3 Island Core Warp Stones", types: ["Island Core","Warp Stone",] },
  { name: "Have an S rank or higher shown on the Town menu", types: ["Rank","Town",] },
  { name: "Hear ♪ Brawl Breaks Ver.2", types: ["Music","Ashuri","Kotri",] },
];
bingoList[8] = [
  { name: "Lv.2 Bunny Strike", types: ["Slide","Bunny Strike",] },
  { name: "Lv.2 Wall Jump", types: ["Slide","Wall Jump",] },
  { name: "Air Dash", types: ["Slide","Air Dash",] },
  { name: "Lv.3 Charge Ring", types: ["Ring","Magic","Cocoa",] },
  { name: "Lv.2 Plus Necklace", types: ["Necklace","Magic",] },
  { name: "Kill a house", types: ["Cocoa Bomb",] },
  { name: "Kill a Thwomp", types: ["Cocoa Bomb",] },
  { name: "Health Surge Badge", types: ["Health Surge","Badge",] },
  { name: "Cashback Badge", types: ["Cashback","Badge",] },
  { name: "Arm Strength and Carrot Boost Badges", types: ["Arm Strength","Carrot Boost","Badge",] },
  { name: "Recruit Aruraune", types: ["Recruit","Aruraune",] },
  { name: "Defeat Shadow Rita", types: ["Boss","Nixie",] },
  { name: "Defeat Illusion Alius II", types: ["Boss","Alius","Ch3",] },
  { name: "Defeat UPRPRC Evernight Peak", types: ["UPRPRC",] },
  { name: "Purchase the HP Regen Buff", types: ["Buff","Aruraune",] },
  { name: "Log the Burn debuff", types: ["Buff","Red","Kotri",] },
  { name: "Log the Null Slow buff", types: ["Buff","Pandora",] },
  { name: "Log the Bunny Lover buff", types: ["Buff","Eggs","Miru",] },
  { name: "10 Mana Up Potions", types: ["Mana Up",] },
  { name: "5 Regen Up Potions", types: ["Regen Up",] },
  { name: "10 Easter Eggs", types: ["Eggs",] },
  { name: "10 Southern Woodland items", types: ["Southern Woodland","Collection",] },
  { name: "10 Western Coast items", types: ["Western Coast","Collection",] },
  { name: "3 Western Coast Attack Up Potions", types: ["Western Coast","Attack Up",] },
  { name: "4 Island Core Mana Up Potions", types: ["Island Core","Mana Up",] },
  { name: "4 Northern Tundra Mana Up Potions", types: ["Northern Tundra","Mana Up",] },
  { name: "4 Eastern Highlands Health Up Potions", types: ["Eastern Highlands","Health Up",] },
  { name: "1 Subterranean Area Warp Stone", types: ["Subterranean Area","Warp Stone",] },
  { name: "10 Warp Stones", types: ["Warp Stone",] },
  { name: "Have an SS rank or higher shown on the Town menu", types: ["Rank","Town",] },
  { name: "Hear ♪ Volcanic Canerns", types: ["Music","Subterranean Area",] },
  { name: "Have at least 80 max MP", types: ["Mana Up",] },
  { name: "Defeat a Lv.10 or higher boss", types: ["Boss",] },
];
bingoList[9] = [
  { name: "Fire Orb", types: ["Subterranean Area","Fire Orb",] },
  { name: "Nature Orb", types: ["Aruraune","Nature Orb",] },
  { name: "Lv.2 Piko Hammer", types: ["Hammer",] },
  { name: "Lv.3 Bunny Amulet", types: ["Amulet","Ch2",] },
  { name: "Lv.3 Bunny Strike", types: ["Slide","Bunny Strike",] },
  { name: "Hammer Roll", types: ["Whirl","Roll","Hammer",] },
  { name: "Spike Barrier", types: ["Slide","Spike",] },
  { name: "Lv.3 Plus Necklace", types: ["Necklace","Magic",] },
  { name: "Kill Cicini's Desk", types: ["Cocoa Bomb","Cicini",] },
  { name: "Survival Badge", types: ["Survival","Badge",] },
  { name: "Health Plus and Surge Badges", types: ["Health Plus","Health Surge","Badge",] },
  { name: "Weaken and Self-Defense Badges", types: ["Weaken","Self-Defense","Badge",] },
  { name: "Recruit Saya", types: ["Recruit","Saya",] },
  { name: "Recruit Rita and Saya", types: ["Recruit","Rita","Saya",] },
  { name: "Defeat Aruraune", types: ["Boss","Aruraune",] },
  { name: "Defeat Lilith I", types: ["Boss","Town2","Lilith",] },
  { name: "Defeat Shadow Rita and Shadow Pandora", types: ["Boss","Pandora","Nixie",] },
  { name: "Purchase 3 Buffs at Once", types: ["Buff",] },
  { name: "Log the Survival Instinct buff", types: ["Buff","Survival","Ch3",] },
  { name: "5 Pack Up Potions", types: ["Pack Up",] },
  { name: "5 Southern Woodland Health Up Potions", types: ["Southern Woodland","Health Up",] },
  { name: "3 Southern Woodland Pack Up Potions", types: ["Southern Woodland","Pack Up",] },
  { name: "4 Island Core Health Up Potions", types: ["Island Core","Health Up",] },
  { name: "4 Island Core Attack Up Potions", types: ["Island Core","Attack Up",] },
  { name: "3 Northern Tundra Regen Up Potions", types: ["Northern Tundra","Regen Up",] },
  { name: "10 Eastern Highlands items", types: ["Eastern Highlands","Collection",] },
  { name: "4 Eastern Highlands Easter Eggs", types: ["Eastern Highlands","Eggs",] },
  { name: "3 Eastern Highlands Warp Stones", types: ["Eastern Highlands","Warp Stone",] },
  { name: "1 Warp Destination Easter Egg", types: ["Warp Destination","Eggs","Ch4",] },
  { name: "Use at least 20 PP", types: ["Pack Up","Badge",] },
  { name: "Equip at least 5 Badges", types: ["Pack Up","Badge",] },
  { name: "15% Item", types: ["Collection",] },
];
bingoList[10] = [
  { name: "Water Orb", types: ["Nieve","Water Orb",] },
  { name: "Lv.2 Light Orb", types: ["Slide","Light Orb",] },
  { name: "Lv.3 Piko Hammer", types: ["Hammer",] },
  { name: "Lv.2 Carrot Bomb", types: ["Carrot Bomb",] },
  { name: "Lv.3 Carrot Bomb", types: ["Carrot Bomb",] },
  { name: "Lv.2 Super Carrot", types: ["Super Carrot","Carrot Bomb",] },
  { name: "Lv.2 Air Dash", types: ["Slide","Air Dash",] },
  { name: "Lv.3 Air Dash", types: ["Slide","Air Dash",] },
  { name: "Lv.2 Hammer Roll", types: ["Whirl","Roll","Hammer",] },
  { name: "Crisis Boost Badge", types: ["Crisis Boost","Badge",] },
  { name: "Hex Cancel Badge", types: ["Hex Cancel","Badge",] },
  { name: "Stamina Plus Badge", types: ["Stamina Plus","Badge",] },
  { name: "Defeat GemaYue", types: ["Ch4",] },
  { name: "Defeat 7 UPRPRC Battles", types: ["UPRPRC",] },
  { name: "Purchase the Giant Buff", types: ["Buff","Saya",] },
  { name: "Log the Cursed debuff", types: ["Buff","Purple",] },
  { name: "Log the Freeze debuff", types: ["Buff","Nixie","Nieve",] },
  { name: "Log the Hex Cancel buff", types: ["Buff","Hex Cancel","Ch4",] },
  { name: "Recruit 5 Towns Members", types: ["Town",] },
  { name: "5 Western Coast Health Up Potions", types: ["Western Coast","Health Up",] },
  { name: "5 Western Coast Easter Eggs", types: ["Western Coast","Eggs",] },
  { name: "10 Island Core items", types: ["Island Core","Collection",] },
  { name: "Have an SSS rank or higher shown on the Town menu", types: ["Rank","Town",] },
  { name: "Hear ♪ Bounce Bounce", types: ["Music","Nieve","Nixie","Keke Bunny","Seana",] },
  { name: "Hear ♪ Deep Under the Sea", types: ["Music","Northern Tundra",] },
];
bingoList[11] = [
  { name: "Lv.2 Fire Orb", types: ["Subterranean Area","Fire Orb",] },
  { name: "Lv.3 Super Carrot", types: ["Super Carrot","Carrot Bomb",] },
  { name: "Lv.3 Wall Jump", types: ["Slide","Wall Jump",] },
  { name: "Lv.3 Hammer Roll", types: ["Whirl","Roll","Hammer",] },
  { name: "Lv.2 Spike Barrier", types: ["Slide","Spike",] },
  { name: "Hold 4 Cocoa Bombs at Once", types: ["Cocoa Bomb","Cocoa","Town",] },
  { name: "Health Wager Badge", types: ["Health Wager","Badge",] },
  { name: "Tough Skin Badge", types: ["Tough Skin","Badge","Ashuri",] },
  { name: "10 Badges", types: ["Badge",] },
  { name: "Hex Cancel and Lucky Seven Badges", types: ["Hex Cancel","Lucky Seven","Badge",] },
  { name: "Recruit Ashuri", types: ["Recruit","Ashuri",] },
  { name: "Defeat Nieve", types: ["Boss","Nieve",] },
  { name: "Purchase the MP Regen Buff", types: ["Buff","Lilith",] },
  { name: "Purchase 4 Buffs at Once", types: ["Buff",] },
  { name: "10 Attack Up Potions", types: ["Attack Up",] },
  { name: "5 Regen Up and 5 Pack Up", types: ["Regen Up","Pack Up",] },
  { name: "6 Southern Woodland Mana Up Potions", types: ["Southern Woodland","Mana Up",] },
  { name: "3 Southern Woodland Regen Up Potions", types: ["Southern Woodland","Regen Up",] },
  { name: "10 Northern Tundra items", types: ["Northern Tundra","Collection",] },
  { name: "4 Eastern Highlands Mana Up Potions", types: ["Eastern Highlands","Mana Up",] },
  { name: "4 Subterranean Area Easter Eggs", types: ["Subterranean Area","Eggs",] },
  { name: "35% Subterranean Area Map", types: ["Subterranean Area","Map",] },
  { name: "50% Warp Destination Map", types: ["Warp Destination","Map","Ch4",] },
  { name: "Get a High-Score above 3000 on the sandbag", types: ["Sandbag","Attack Up",] },
  { name: "Have at least 300 max HP", types: ["Health Up",] },
  { name: "Have at least 130 max MP", types: ["Mana Up",] },
  { name: "15% Map", types: ["Map",] },
];
bingoList[12] = [
  { name: "Lv.2 Nature Orb", types: ["Aruraune","Nature Orb",] },
  { name: "Lv.3 Light Orb", types: ["Slide","Light Orb",] },
  { name: "Air Jump", types: ["Air Jump","System Interior","Cicini","Syaro",] },
  { name: "Lv.3 Spike Barrier", types: ["Slide","Spike",] },
  { name: "Quick Barrette, Charge Ring, Plus Necklace, and Auto Earrings", types: ["Barrette","Ring","Necklace","Earrings",] },
  { name: "Pure Love Badge", types: ["Pure Love","Badge",] },
  { name: "Top Form Badge", types: ["Top Form","Badge",] },
  { name: "ATK Trade, Crisis Boost, and Arm Strength Badges", types: ["ATK Trade","Crisis Boost","Arm Strength","Badge",] },
  { name: "Recruit Kotri", types: ["Recruit","Kotri",] },
  { name: "Recruit Syaro", types: ["Recruit","Cicini","Syaro","System Interior",] },
  { name: "Recruit Ashuri, Pandora, and Rita", types: ["Recruit","Ashuri","Pandora","Rita",] },
  { name: "Defeat Pink Kotri", types: ["Boss","Kotri",] },
  { name: "Defeat Seana I", types: ["Boss","Seana",] },
  { name: "Defeat Robot Maids", types: ["System Interior",] },
  { name: "Defeat Rainbow Crystals", types: ["Town","Ashuri",] },
  { name: "Defeat 3 Otaku Battles", types: ["Ch4",] },
  { name: "End with 50000 EN", types: ["Money",] },
  { name: "Purchase the Shrink Buff", types: ["Buff","Ashuri",] },
  { name: "Recruit 6 Towns Members", types: ["Town",] },
  { name: "15 Health Up Potions", types: ["Health Up",] },
  { name: "15 Easter Eggs", types: ["Eggs",] },
  { name: "15 Southern Woodland items", types: ["Southern Woodland","Collection",] },
  { name: "15 Western Coast items", types: ["Western Coast","Collection",] },
  { name: "2 Northern Tundra Pack Up Potions", types: ["Northern Tundra","Pack Up",] },
  { name: "4 Northern Tundra Warp Stones", types: ["Northern Tundra","Warp Stone",] },
  { name: "4 Eastern Highlands Pack Up Potions", types: ["Eastern Highlands","Pack Up",] },
  { name: "Hear ♪ cyberspace.exe", types: ["Music","System Interior",] },
  { name: "Equip at least 6 Badges", types: ["Pack Up","Badge",] },
];
bingoList[13] = [
  { name: "Lv.3 Fire Orb", types: ["Subterranean Area","Fire Orb",] },
  { name: "Lv.2 Water Orb", types: ["Nieve","Water Orb",] },
  { name: "Strange Box", types: ["Town","Syaro",] },
  { name: "Sunny Beam, Chaos Rod, Healing Staff, Explode Shot, and Rainbow Shot", types: ["Yellow","Purple","Green","Red","Rainbow",] },
  { name: "Slide Powder, Air Jump, Air Dash, and Wall Jump", types: ["Slide","Air Jump","Air Dash","Wall Jump",] },
  { name: "Obtain a Gold Carrot", types: ["Gold Carrot",] },
  { name: "Health and Mana Wager Badges", types: ["Health Wager","Mana Wager","Badge",] },
  { name: "Recruit Nieve and Nixie", types: ["Recruit","Nieve","Nixie",] },
  { name: "Recruit Lilith", types: ["Town2","Cicini","Lilith",] },
  { name: "Recruit Aruraune and Lilith", types: ["Recruit","Aruraune","Lilith",] },
  { name: "Recruit Kotri and Pandora", types: ["Recruit","Kotri","Pandora",] },
  { name: "Recruit Nieve, Nixie, and Cocoa", types: ["Recruit","Cocoa","Nieve","Nixie",] },
  { name: "Defeat Syaro", types: ["Boss","Cicini","Syaro","System Interior",] },
  { name: "Defeat Nixie", types: ["Boss","Nieve","Nixie",] },
  { name: "Purchase the Amulet Cut Buff", types: ["Buff","Kotri",] },
  { name: "Purchase the Give ATK Down Buff", types: ["Buff","Nixie",] },
  { name: "Purchase the Give DEF Down Buff", types: ["Buff","Nieve",] },
  { name: "Log the Null Melee buff", types: ["Buff","System Interior",] },
  { name: "10 Health Up and 10 Mana Up", types: ["Health Up","Mana Up",] },
  { name: "6 Western Coast Mana Up Potions", types: ["Western Coast","Mana Up",] },
  { name: "3 Western Coast Pack Up Potions", types: ["Western Coast","Pack Up",] },
  { name: "3 Island Core Regen Up Potions", types: ["Island Core","Regen Up",] },
  { name: "7 Island Core Easter Eggs", types: ["Island Core","Eggs",] },
  { name: "Defeat a Lv.15 or higher boss", types: ["Boss",] },
  { name: "20% Item", types: ["Collection",] },
];
bingoList[14] = [
  { name: "Lv.3 Water Orb", types: ["Nieve","Water Orb",] },
  { name: "Lv.3 Nature Orb", types: ["Aruraune","Nature Orb",] },
  { name: "Mana Plus Badge", types: ["Mana Plus","Badge",] },
  { name: "Mana Plus and Surge Badges", types: ["Mana Plus","Mana Surge","Badge",] },
  { name: "End with 60000 EN", types: ["Money",] },
  { name: "15 Mana Up Potions", types: ["Mana Up",] },
  { name: "10 Regen Up Potions", types: ["Regen Up",] },
  { name: "4 Western Coast Warp Stones", types: ["Western Coast","Warp Stone",] },
  { name: "15 Island Core items", types: ["Island Core","Collection",] },
  { name: "15 Eastern Highlands items", types: ["Eastern Highlands","Collection",] },
  { name: "6 Eastern Highlands Attack Up Potions", types: ["Eastern Highlands","Attack Up",] },
  { name: "6 System Interior items", types: ["System Interior","Collection",] },
  { name: "40% System Interior Map", types: ["System Interior","Map",] },
  { name: "Have a MAX rank shown on the Town menu", types: ["Rank","Town",] },
  { name: "Use at least 30 PP", types: ["Pack Up","Badge",] },
  { name: "Have at least 180 max MP", types: ["Mana Up","Badge",] },
  { name: "20% Map", types: ["Map",] },
];
bingoList[15] = [
  { name: "Recruit Ashuri and Lilith", types: ["Recruit","Ashuri","Lilith",] },
  { name: "Purchase 5 Buffs at Once", types: ["Buff",] },
  { name: "Recruit 7 Towns Members", types: ["Town",] },
  { name: "10 Pack Up Potions", types: ["Pack Up",] },
  { name: "70% Island Core Map", types: ["Island Core","Map",] },
  { name: "3 Eastern Highlands Regen Up Potions", types: ["Eastern Highlands","Regen Up",] },
  { name: "70% Eastern Highlands Map", types: ["Eastern Highlands","Map",] },
  { name: "Equip at least 7 Badges", types: ["Pack Up","Badge",] },
  { name: "Have at least 500 max HP", types: ["Health Up",] },
];
bingoList[16] = [
  { name: "Fire, Water, Nature, and Light Orbs", types: ["Fire Orb","Water Orb","Nature Orb","Light Orb",] },
  { name: "End with 70000 EN", types: ["Money",] },
  { name: "20 Easter Eggs", types: ["Eggs",] },
  { name: "20 Southern Woodland items", types: ["Southern Woodland","Collection",] },
  { name: "20 Western Coast items", types: ["Western Coast","Collection",] },
  { name: "15 Northern Tundra items", types: ["Northern Tundra","Collection",] },
  { name: "5 Northern Tundra Health Up Potions", types: ["Northern Tundra","Health Up",] },
  { name: "7 Northern Tundra Easter Eggs", types: ["Northern Tundra","Eggs",] },
  { name: "15 Warp Stones", types: ["Warp Stone",] },
  { name: "Defeat a Lv.20 or higher boss", types: ["Boss",] },
  { name: "25% Map", types: ["Map",] },
];
bingoList[17] = [
  { name: "15 Badges", types: ["Badge",] },
  { name: "Top Form and Tough Skin Badges", types: ["Top Form","Tough Skin","Badge",] },
  { name: "20 Health Up Potions", types: ["Health Up",] },
  { name: "15 Attack Up Potions", types: ["Attack Up",] },
  { name: "75% Southern Woodland Map", types: ["Southern Woodland","Map",] },
  { name: "10 Western Coast Easter Eggs", types: ["Western Coast","Eggs","Halloween",] },
  { name: "60% Western Coast Map", types: ["Western Coast","Map",] },
  { name: "75% Western Coast Map", types: ["Western Coast","Map","Halloween",] },
  { name: "70% Northern Tundra Map", types: ["Northern Tundra","Map",] },
  { name: "Have 2 MAX ranks shown on the Town menu", types: ["Rank","Town",] },
  { name: "Have at least 230 max MP", types: ["Mana Up","Badge",] },
];
bingoList[18] = [
  { name: "Defeat Twin Cats", types: ["Plurkwood",] },
  { name: "Recruit 8 Towns Members", types: ["Town",] },
  { name: "4 Health, Mana, Regen, Pack, Attack Up", types: ["Health Up","Mana Up","Regen Up","Pack Up","Attack Up",] },
  { name: "8 Southern Woodland Easter Eggs", types: ["Southern Woodland","Eggs",] },
  { name: "5 Northern Tundra Attack Up Potions", types: ["Northern Tundra","Attack Up",] },
  { name: "20 Eastern Highlands items", types: ["Eastern Highlands","Collection",] },
  { name: "3 Plurkwood Easter Eggs", types: ["Plurkwood","Eggs",] },
  { name: "Get a High-Score above 5000 on the sandbag", types: ["Sandbag","Attack Up",] },
  { name: "Have at least 700 max HP", types: ["Health Up","Badge",] },
  { name: "25% Item", types: ["Collection",] },
];
bingoList[19] = [
  { name: "P Hairpin", types: ["P Hairpin","Plurkwood",] },
  { name: "Recruit Keke Bunny", types: ["Town2","Keke Bunny","Plurkwood",] },
  { name: "20 Mana Up Potions", types: ["Mana Up",] },
  { name: "20 Island Core items", types: ["Island Core","Collection",] },
  { name: "90% Island Core Map", types: ["Island Core","Map",] },
  { name: "Use at least 40 PP", types: ["Pack Up","Badge",] },
  { name: "End with 80000 EN", types: ["Money",] },
];
bingoList[20] = [
  { name: "Lv.2 P Hairpin", types: ["P Hairpin","Plurkwood",] },
  { name: "Recruit 9 Towns Members", types: ["Town",] },
  { name: "15 Regen Up Potions", types: ["Regen Up",] },
  { name: "25 Easter Eggs", types: ["Eggs",] },
  { name: "25 Southern Woodland items", types: ["Southern Woodland","Collection",] },
  { name: "25 Western Coast items", types: ["Western Coast","Collection",] },
  { name: "90% Eastern Highlands Map", types: ["Eastern Highlands","Map",] },
  { name: "Have at least 260 max MP", types: ["Mana Up","Badge",] },
  { name: "Defeat a Lv.25 or higher boss", types: ["Boss",] },
  { name: "30% Map", types: ["Map",] },
];
bingoList[21] = [
  { name: "Lv.3 P Hairpin", types: ["P Hairpin","Plurkwood",] },
  { name: "Start the Halloween Event", types: ["Cicini","Syaro","Vanilla","Chocolate","Lilith","Halloween",] },
  { name: "15 Pack Up Potions", types: ["Pack Up",] },
  { name: "10 Regen Up and 10 Pack Up", types: ["Regen Up","Pack Up",] },
  { name: "20 Northern Tundra items", types: ["Northern Tundra","Collection",] },
  { name: "100% Plurkwood Map", types: ["Plurkwood","Map",] },
  { name: "18 Warp Stones", types: ["Warp Stone",] },
  { name: "5 Health, Mana, Regen, Pack, Attack Up", types: ["Health Up","Mana Up","Regen Up","Pack Up","Attack Up",] },
];
bingoList[22] = [
  { name: "20 Badges", types: ["Badge",] },
  { name: "Recruit Seana", types: ["Town2","Cicini","Syaro","Chocolate","Vanilla","Nieve","Nixie","Seana",] },
  { name: "End with 99999 EN", types: ["Money",] },
  { name: "Recruit 10 Towns Members", types: ["Town",] },
  { name: "25 Health Up Potions", types: ["Health Up",] },
  { name: "90% Northern Tundra Map", types: ["Northern Tundra","Map",] },
  { name: "25 Eastern Highlands items", types: ["Eastern Highlands","Collection",] },
  { name: "End with 90000 EN", types: ["Money",] },
];
bingoList[23] = [
  { name: "Purchase the Attack Up Buff", types: ["Buff","Seana",] },
  { name: "Hear ♪ Mischievous Masquerade", types: ["Music","Cicini","Syaro","Vanilla","Chocolate","Lilith","Halloween",] },
  { name: "Log the Endurance buff", types: ["Buff","Seana",] },
  { name: "Log the Fatigue debuff", types: ["Buff","Seana",] },
  { name: "20 Attack Up Potions", types: ["Attack Up",] },
  { name: "6 Health, Mana, Regen, Pack, Attack Up", types: ["Health Up","Mana Up","Regen Up","Pack Up","Attack Up",] },
  { name: "Have at least 900 max HP", types: ["Health Up","Badge",] },
  { name: "Have at least 290 max MP", types: ["Mana Up","Badge","Buff",] },
  { name: "30% Item", types: ["Collection",] },
  { name: "35% Map", types: ["Map",] },
];
bingoList[24] = [
  { name: "Defeat Miru", types: ["Boss","Miru","Ch5",] },
  { name: "Hear ♪ M.R.", types: ["Music","Miru",] },
  { name: "15 Health Up and 15 Mana Up", types: ["Health Up","Mana Up",] },
  { name: "Log the Lucky Seven buff", types: ["Buff","Miru","Halloween",] },
  { name: "Log the Health Absorb buff", types: ["Buff","Cicini","Syaro","Vanilla","Chocolate","Lilith","Halloween","DEF Grow",] },
  { name: "Log the Power Absorb buff", types: ["Buff","Cicini","Syaro","Vanilla","Chocolate","Lilith","Halloween",] },
  { name: "3 Warp Destination Easter Eggs", types: ["Warp Destination","Eggs","Ch5",] },
  { name: "90% Warp Destination Map", types: ["Warp Destination","Map","Ch5",] },
  { name: "Hear ♪ The Truth Never Spoken", types: ["Music","Noah","Ch5",] },
  { name: "Hear ♪ Unfamiliar Place Again", types: ["Music","Ch5",] },
];
bingoList[25] = [
  { name: "Defeat the Halloween Cats", types: ["Boss","Cicini","Syaro","Vanilla","Chocolate","Lilith","Halloween",] },
  { name: "Log the Double Damage buff", types: ["Buff","Miru",] },
  { name: "Use at least 50 PP", types: ["Pack Up","Badge",] },
  { name: "25 Mana Up Potions", types: ["Mana Up",] },
  { name: "Get a High-Score above 7000 on the sandbag", types: ["Sandbag","Attack Up",] },
  { name: "Recruit 11 Towns Members", types: ["Town",] },
];